### ISSUE TITLE
Brindar apoyo a las conferencias de Angular

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#15]
¡Las conferencias administradas por la comunidad como ngColombia, ngBolivia, ngSpain, etc. son excelentes!

@anacidre @Elecash @luixaviles cuáles son algunos de los mayores desafíos que enfrentan estas conferencias? Si podemos identificar esos desafíos aquí, podemos decidir cuáles podríamos resolver y luego priorizarlos.

**Comment by Elecash** [comment]
@Splaktar para mi los principales desafíos (por orden de importancia) son:

1. Encontrar un lugar adecuado donde hacerlo y poder pagarlo (o si es gratis mejor). Si tienes un buen sitio donde hacerlo ya tienes mucho ganado, ya que en realidad no se necesita mucho más si uno lo piensa bien.
2. Poder pagar catterings para los asistentes. Esto normalmente con sponsors lo puedes hacer o con el pago de la entrada.
3. Traer a los speakers. Según el presupuesto podrás traer más y que vengan de más lejos, aunque lo realmente importante es conocer a tu audiencia y tener buenos contactos para poder traer a los mejores speakers para esa audiencia.

Una vez tienes estas tres cosas, el resto viene solo.

**Comment by anacidre** [comment]
Estoy totalmente de acuerdo con @Elecash ! Pero también me resulta difícil definir un timeline, de cuando deberíamos de tener cada cosa hecha como CFP, venta entradas, etc.

**Comment by alfredobonillaGL** [comment]
Pienso que sería muy útil tener una plantilla de todas las cosas que hay que tomar en cuenta y además cuales personas pueden fungir como mentores para ayudar a que nuevas conferencias inicien. Por ejemplo, en Costa Rica, una vez que la comunidad tome un poco más de ritmo, queremos hacer una conferencia y estoy seguro que tendremos muchas preguntas al respecto.

**Comment by brolag** [comment]
Pienso que sería muy útil tener una plantilla de todas las cosas que hay que tomar en cuenta y además cuales personas pueden fungir como mentores para ayudar a que nuevas conferencias inicien. Por ejemplo, en Costa Rica, una vez que la comunidad tome un poco más de ritmo, queremos hacer una conferencia y estoy seguro que tendremos muchas preguntas al respecto.

**Comment by Splaktar** [comment]
@all-contributors please add @Elecash for ideas

**Comment by Splaktar** [comment]
@all-contributors please add @anacidre for ideas
