### ISSUE TITLE
Planifique la incorporación gradual y el lanzamiento lento de chat.angular.lat

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#16]
## Plan de abril
- [x] Continuar invitando a los organizadores de eventos de Angular
- [x] #1
- [x] #13
- [ ] #14 
- [ ] #6 
- [ ] #8 
- [x] Considere la incorporación de miembros de grupos de reuniones cuyos organizadores sean parte de Angular Latino
- [ ] Considere permitir que todos los miembros actuales de Mattermost inviten a otros a unirse al chat

## Plan de mayo
- [x] Considere hacer algún tipo de anuncio público en ng-conf
- [x] Considere la posibilidad de abrir temporalmente el registro de Mattermost al público
- [x] Determinar las próximas conferencias para la asociación
    1. [ngSpain](https://ngspain.com/) 19-20 oct 2019
    1. [ngColombia](https://ngcolombia.com/) ~~[2019](https://medium.com/@jdjuan/ngcolombia-will-be-postponed-until-2020-fcdad89feecf)~~
    1. [ngBolivia](https://ng-bolivia.org/) 23-24 de agosto 2019
    1. [otras](https://angularconferences.com/)?
- [x] Solucione cualquier problema de rendimiento, organización y espacio en disco.

## Plan de junio
1. Determine si es viable abrir permanentemente el registro al público.
    1. Formule un plan para cuando sucederá y cómo apoyarlo

**Comment by Splaktar** [comment]
Planeo hablar de Angular Hispano sobre Angular Hispano este miércoles. Estoy considerando la posibilidad de abrir invitaciones al chat para los espectadores generales de Angulareando. Por favor, déjame saber lo que piensas de esto.

**Comment by mahcr** [comment]
@Splaktar 
Podríamos trabajar en filtrar https://angularconferences.com/ con los países latinoamericanos y mostrarlos en la pagina

**Comment by Splaktar** [comment]
@all-contributors please add @mahr for ideas

**Comment by Splaktar** [comment]
@all-contributors please add @mahcr for ideas
