### ISSUE TITLE
web: añadir sección para patrocinadores

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#21]
Debemos agregar una sección para patrocinadores que incluya lo siguiente hasta ahora
- Google Cloud Platform
- DevIntent

**Comment by AXEL1988** [comment]
@Splaktar  tengo lista esta sección.

**Comment by Splaktar** [comment]
Closed by https://github.com/angular-hispano/angular-hispano/commit/ffdec21407d5643e54752f0125374c49ac600025.
