### ISSUE TITLE
web: crear una página para listar conferencias en países de habla hispana

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#24]
Sugerido por @mahcr en https://github.com/angular-hispano/angular-hispano/issues/16#issuecomment-483892072

**Comment by AXEL1988** [comment]
Qué ideas pueden aportar para este punto?
@march sugiere filtrar de este sitio # 16 (comment) y se me ocurre mantener un patrón similar pero ya con los filtros realizados.

**Comment by alfredobonillaGL** [comment]
Pienso que podrían incluirse algunos filtros por país, y también información sobre los puntos de contacto con los organizadores para que también podamos trabajar en conjunto en la región.

**Comment by brolag** [comment]
Pienso que podrían incluirse algunos filtros por país, y también información sobre los puntos de contacto con los organizadores para que también podamos trabajar en conjunto en la región.

**Comment by Cristian-Hernandez** [comment]
seria interesante que se pueda visualizar de forma cronológica ¿Cuáles son los siguientes eventos de las diferentes comunidades regionales? como Meetup, Streaming, etc.

**Comment by Splaktar** [comment]
Podríamos usar la API de Meetup para obtener información sobre las reuniones. En el pasado, requerían una clave API de cada capítulo para obtener los datos completos. Pero ahora se han cambiado a OAuth y no estoy seguro de cómo eso afecta el acceso a la API.

Sin embargo, creo que los organizadores deberían ingresar manualmente eventos como conferencias, podcasts en vivo o hangouts de videos. Podríamos crear una UI para esto (respaldada por Firestore) o simplemente codificarla en un archivo JSON que pueda ser actualizado por los PRs.

**Comment by Cristian-Hernandez** [comment]
Me parece viable la opción de que los organizadores lo carguen manualmente @Splaktarl, debido a que describirían con mayor detalle del evento.

**Comment by Splaktar** [comment]
@all-contributors please add @Cristian-Hernandez for ideas

**Comment by Splaktar** [comment]
@all-contributors please add @brolag for ideas
