### ISSUE TITLE
cuba: ¿Restringido?

### ISSUE THREAD

**Issue by mailok** [angular-hispano/angular-hispano#28]
Les escribo porque recientemente me uní a la comunidad de Angular Hispano, y tengo un problemas con esto que quizás me puedan ayudar. El problema es el siguiente, yo solo puedo entrar al sitio de la cominidad de Angular Hispano con Proxy anónimo porque al parecer
está restringido para acá para Cuba que es de donde vivo. Entonces la página de Angular Hispano me dá un error diciendo que tiene problemas con el Websocket, quizás por el proxy anónimo. Entonces mi inquetud es la siguiente, exsisten posibilidades de que no esté restringido  para Cuba?

![Captura](https://user-images.githubusercontent.com/3769277/56465413-9ec89580-63ca-11e9-8768-91c91b3a25b7.PNG)

**Comment by Splaktar** [comment]
Gracias por informarnos sobre esto.

Esto es algo que voy a tener que investigar más a fondo. El servidor está alojado en los EE. UU. En la plataforma Google Cloud y la financiación proviene de empresas de EE. UU. Esto significa que tendremos que cumplir con las restricciones legales de los Estados Unidos.

Sin duda, me gustaría involucrar a la comunidad Angular cubana, pero debemos asegurarnos de que no estamos violando ninguna ley del Departamento de Estado de los EE. UU.

**Comment by mailok** [comment]
@Splaktar Gracias, eso debe ser por estar en los servidores de EEUU. Supongo que aqui quizás no se pueda hacer mucho. Gracias de todas maneras.

**Comment by orestes** [comment]
¿Qué tal si hacemos un mirror para estos países, que esté alojado en España? Aquí no tenemos estos problemas. No se como de complicado sería hacer algo así con Mattermost

**Comment by Splaktar** [comment]
Si hay una plataforma de alojamiento web en España que no es propiedad de una empresa estadounidense, podría funcionar para el sitio web. Pero Firebase, GitHub y muchos otros no funcionarán. ¿Hay algo como esto que tenga alojamiento web gratuito en España?

Solo los ciudadanos no estadounidenses podrían desplegarse en él, etc.

Posiblemente podríamos alojarlo en cuba.angular.lat ...

Hacer algo similar para Mattermost sería más desafiante y posiblemente costoso, a menos que una empresa en España pudiera patrocinarlo.

**Comment by Splaktar** [comment]
Probablemente también significaría que DevIntent, mi compañía, ya no podría patrocinarlo, ya que estamos ubicados en los EE. UU. Y debemos cumplir con las leyes relacionadas con las sanciones.

Es un tema complicado seguro.

**Comment by orestes** [comment]
Uumh. Entiendo. Si surgiera la necesidad yo podría patrocinar un mirror en Europa. Supongo que la gente que tiene estos problemas a menudo están acostumbrados a usar proxies y demás.
De todos modos, si en un futuro fuera una ayuda, dejo mi oferta aquí :)

**Comment by mailok** [comment]
@orestes  genial!!, muchas gracias
