### ISSUE TITLE
Crear un código de conducta.

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#3]
- [x] Crearlo
- [x] Añadir a sitio web

El trabajo está en curso en este [Google Doc](https://docs.google.com/document/d/1E_yEVlpcuaRl4DEhCzf86F7hkUATRE3cJA--wuJRf2o/edit?usp=sharing).

**Comment by Villanuevand** [comment]
@maleja111 [en este enlace ](https://docs.google.com/document/d/1E_yEVlpcuaRl4DEhCzf86F7hkUATRE3cJA--wuJRf2o/edit) está el CoC que estamos traduciendo. 
Es el CoC de la comunidad [GDG  Space Coast](http://gdg-x.github.io/boomerang/#!/conduct)

**Comment by Villanuevand** [comment]
@maleja111 [en este enlace ](https://docs.google.com/document/d/1E_yEVlpcuaRl4DEhCzf86F7hkUATRE3cJA--wuJRf2o/edit) está el CoC que estamos traduciendo. 
Es el CoC de la comunidad [GDG  Space Coast](http://gdg-x.github.io/boomerang/#!/conduct)

**Comment by Splaktar** [comment]
Debemos asegurarnos de que el nuevo CoC también capture la esencia del CoC angular (https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md).

El que estamos utilizando es una combinación de varios CoC que se utilizan en todos los GDG de todo el mundo.

**Comment by Splaktar** [comment]
En https://github.com/angular-latino/angular-latino/issues/5#issuecomment-477264721, @maleja111 mencionó un CoC usado en Colombia (https://github.com/colombia-dev/codigo-de -conducta). Deberíamos ver si podemos usar parte de ese contenido también en nuestro nuevo CoC.

**Comment by Splaktar** [comment]
El CoC de ngColombia: https://ngcolombia.com/coc

**Comment by maleja111** [comment]
!Hola!
Esta es una propuesta para el CoD
https://docs.google.com/document/d/1GuXz6TwD5SZ8i3ZQVdtSWkCfZueCl77YqyawzJw_Fbc/edit?usp=sharing
Es una unión entre el CoC angular 
CoC Colombia dev (pedí permiso a uno de los organizadores, y me dijo que cero problema que era open source)
y CoC de She Codes Angular creado por @vanessamarely 
(https://shecodes.gitbook.io/she-codes-angular/codigo-de-conducta)
Siéntanse libre de adicionar o eliminar, los comentarios están habilitados

**Comment by Villanuevand** [comment]
@maleja111 / @vanessamarely  

¡Increible trabajo!. Para mi esta muy acorde a lo que es y será nuestra comunidad.

**Comment by Splaktar** [comment]
> Esta es una propuesta para el CoC
https://docs.google.com/document/d/1GuXz6TwD5SZ8i3ZQVdtSWkCfZueCl77YqyawzJw_Fbc/edit?usp=sharing

Revisé las dos primeras secciones y se ven muy bien. Acabo de dejar un comentario sobre las discusiones políticas.

**Comment by Splaktar** [comment]
> Esta es una propuesta para el CoC
https://docs.google.com/document/d/1GuXz6TwD5SZ8i3ZQVdtSWkCfZueCl77YqyawzJw_Fbc/edit?usp=sharing

He terminado de revisar esto y sugerir comentarios. Todavía necesito analizar los otros CoC sugeridos para determinar si a esta versión le falta algo. Es importante que no permitamos que ningún comportamiento tóxico se escape por las grietas de la política.

¡Muchas gracias por su trabajo en esta política crítica!

**Comment by Splaktar** [comment]
https://www.javascriptandfriends.com/codeofconduct tiene algunas ideas interesantes que han extraído de otros CoC.

Creo que deberíamos considerar agregar una sección similar a esta (traducida aproximadamente al español):

----

Priorizamos la seguridad de las personas marginadas sobre la comodidad de las personas privilegiadas. Nos reservamos el derecho de no actuar sobre las quejas relacionadas con:

- El "racismo inverso", "sexismo inverso" y "cisfobia"
- Comunicación razonable de límites, como "déjame en paz", "vete" o "no estoy discutiendo esto contigo"
- Al comunicarse en un ‘tono’, no se encuentra agradable
- Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas.

**Comment by Splaktar** [comment]
@maleja111 @vanessamarely ¿qué te parece?

**Comment by Splaktar** [comment]
Planeo hablar de Angular Hispano sobre Angular Hispano este miércoles. Estoy considerando la posibilidad de abrir invitaciones al chat para los espectadores generales de Angulareando.

Sin embargo, me gustaría finalizar el Código de conducta antes de esa fecha.

**Comment by maleja111** [comment]
hola @Splaktar 
ya adicione los cambios, acepte las solicitudes y comentarios
aun que incluí todas tus sugerencias, personalmente tengo dudas en las siguientes dos:

El "racismo inverso", "sexismo inverso" y "cisfobia"
(Si se llega a presentar un caso real en este aspecto, ¿cómo se va a manejar esta situación?)

Adicionaría a este:
Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas.
En caso de ser testigo de este comportamiento, se deberá realizar una denuncia formal, no indisponer a los miembros de la comunidad con comentarios negativos.

**Comment by Splaktar** [comment]
> El "racismo inverso", "sexismo inverso" y "cisfobia"
(Si se llega a presentar un caso real en este aspecto, ¿cómo se va a manejar esta situación?)

Aquí se ofrecen opciones de liderazgo para manejar casos en los que una persona privilegiada afirma que se los está discriminando por su raza, sexo u orientación sexual. En algunos casos, especialmente en la historia reciente, los abusadores usan esto para intimidar o intentar vengarse de sus víctimas.

Esta cláusula deja claro que el liderazgo tiene la opción de determinar que no se tomarán medidas en este tipo de casos en lugar de ser "forzados" a castigar a una persona marginada basándose en un informe de una persona privilegiada.

Claramente, este tipo de caso necesitaría una discusión entre los líderes para determinar cómo manejar mejor la situación. También puede requerir entrevistas con las partes involucradas.

**Comment by Splaktar** [comment]
> Nos reservamos el derecho de no actuar sobre las quejas relacionadas con:
> - Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas.

Esta declaración aclara que nos reservamos el derecho de no castigar a las personas que denuncian y critican estos comportamientos. Queremos animar a las personas a que expresen su opinión inmediatamente cuando ven estos comportamientos y no teman que puedan ser castigados por hacerlo. Queremos que se llame la atención y se detenga de inmediato en lugar de dejar que continúe y enajene a los miembros de la comunidad.

> Adicionaría a este:
En caso de ser testigo de este comportamiento, se deberá realizar una denuncia formal, no indisponer a los miembros de la comunidad con comentarios negativos.

No tengo muy claro lo que quieres decir aquí. ¿Está diciendo que las personas deben guardar silencio cuando ven estos comportamientos y hacer una queja formal por escrito en algún momento en el futuro?

**Comment by Splaktar** [comment]
He agregado mi nombre y el identificador de chat para mensajes directos a la sección que cubre el reporte de violaciones.

¿A quién le gustaría unirse a mí para incluir su nombre como contacto para manejar las infracciones al Código de Conducta (sección 5: https://docs.google.com/document/d/1GuXz6TwD5SZ8i3ZQVdtSWkCfZueCl77YqyawzJw_Fbc/edit?usp=sharing)?

**Comment by maleja111** [comment]
Hola @Splaktar 

en cuanto la duda 1) El "racismo inverso", "sexismo inverso" y "cisfobia"
entiendo el punto y estoy de acuerdo.

en el punto dos:

> No tengo muy claro lo que quieres decir aquí. ¿Estás sugiriendo que las personas deben guardar silencio cuando ven estos comportamientos y hacer una queja formal por escrito en algún momento en el futuro?

en el punto "Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas."
¿qué pasa si esto es real?
por esto adicionaría, que no esta permitido criticar y juzgar , y empezar una discusión sobre su pociones, si es un caso real, deberá realizar una denuncia formar en tales actos, de lo contrario sus criticas y suposiciones serian desestimados. por que a la larga solo esta intentando crear un ambiente hostil con sus "Criticas de comportamientos o suposiciones "

O mejor, 
cambiar
"Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas."
por
"No realizar criticas sobre comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas, sin justificaciones reales que permitan realizar una denuncia formal."
___________________________________
aclarando asi:
(si vas a hablar sobre eso, que sea algo de peso, no un comentario suelto que va a indisponer a otro)

**Comment by Splaktar** [comment]
>> Nos reservamos el derecho de no actuar sobre las quejas relacionadas con:
> > - Criticar comportamientos o suposiciones racistas, sexistas, cissexistas u opresivas.

> Esta declaración aclara que nos reservamos el derecho de no castigar a las personas que denuncian y critican estos comportamientos. Queremos animar a las personas a que expresen su opinión inmediatamente cuando ven estos comportamientos y no teman que puedan ser castigados por hacerlo. Queremos que se llame la atención y se detenga de inmediato en lugar de dejar que continúe y enajene a los miembros de la comunidad.

Creo que debe haber un problema con la traducción aquí. Esperemos que este hilo de Twitter pueda ayudar a explicar la idea: https://twitter.com/StephEvz43/status/1111394650739204096, especialmente este Tweet (https://twitter.com/StephEvz43/status/1111394670876094464).

> ¿qué pasa si esto es real?

Creo que la suposición debería ser creer a alguien que está identificando un comportamiento sexista, racista, etc. y luego escucharlos y determinar si el comportamiento puede cambiarse de inmediato, si es posible.

**Comment by mahcr** [comment]
Hola a todos! Excelente trabajo! Agregue algunas sugerencias al doc. Algunas de ellas pueden estar relacionadas a las diferentes formas que se habla español en cada país.

1. Cambiar `actividades` por `actividad`
> Bajo ese principio queremos enfocar esta comunidad, una comunidad de respeto por el otro, donde cualquiera que sienta pasión por Angular y desee involucrarse con cualquier tipo de **actividades** deberá ayudar a mantener una atmósfera de cortesía por el otro
2. Cambiar `Evitaremos` por `Evitar`
> Evitaremos comportamientos que agredan las expresiones de identidad, género, creencias religiosas, acciones que lastimen o los aíslen a otros.
3. Reemplazar comillas simples por dobles, para que se lea `comunicarse en un "tono",`
> Al comunicarse en un ‘tono’, no se encuentra agradable
4. Algunos de los punto listados en `Comportamiento esperado` utilizan palabras como `No toleramos`, `Rechazamos`, hace referencia a `nosotros` pero no se define quien son `nosotros` tampoco se refiere explicitamente a los organizadores. Sugiero escribir las reglas en infinitivo, tal manera que se lean como: `No hacer`, `Promover` o sin dirijise a ningun sujeto `Se rechaza`, `No se tolera`
5. Será importante agregar un glosario?

**Comment by maleja111** [comment]
Aceptadas las correcciones
Único pendiente es en un fragmento literal adicionado por @Splaktar que me gustaría que lo verificara él
De resto, ¡creo que esta ok para tu reunión mañana!
¡mucha suerte!
y disculpen los días de desconexión los viajes me pasaron factura y me enferme bastante

¡un abrazo a todos! quedo pendiente para más revisiones

**Comment by Splaktar** [comment]
oof! Lamento escuchar que has estado enfermo! Muchas gracias por hacer las actualizaciones.

**Comment by Splaktar** [comment]
Otro CoC del groupo de Lantinx pero en íngles: https://techqueria.org/code-of-conduct/
