### ISSUE TITLE
docs(contribuyendo): crear una guía de colaboradores

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#30]
- [x] crear `/CONTRIBUTING.md`
- [x] escribe la guía
  - [x] Basicos como [configurar SSH](https://help.github.com/en/articles/connecting-to-github-with-ssh)
- [x] usar los issue templates de GitHub
- [x] WebStorm
- [x] Guía de PRs
- [x] Guía de revisiones

Referencias:
- https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md
- https://github.com/angular/angular/blob/master/CONTRIBUTING.md

**Comment by Splaktar** [comment]
Un poco de progreso en https://github.com/angular-hispano/angular-hispano/blob/contributing/CONTRIBUTING.md

**Comment by Splaktar** [comment]
Más progreso en PR https://github.com/angular-hispano/angular-hispano/pull/47

**Comment by Splaktar** [comment]
Tenemos issue templates: https://github.com/angular-hispano/angular-hispano/commit/7242291c804159f91914c0575f50ab7f064282d1

**Comment by Villanuevand** [comment]
En FirebaseVe usamos un `CONTRIBUTING.md` evloucionado [de  NgVenezuela](https://github.com/firebaseve/site-firebase-venezuela/blob/develop/.github/CONTRIBUTING.md),  quizás podriamos tomar algo de allí tambien?. 

Ambos contributing tiene como base los del proyecto de Angular, pero ya están traducidos al español y adaptados.

**Comment by Splaktar** [comment]
> - Usa `title-casing` (AP style).

@Villanuevand para que es eso? el nombre de rama? titulo de PR?

**Comment by Villanuevand** [comment]
@Splaktar si, creo que era para el título de PR...
