### ISSUE TITLE
web: añadir un pie de página

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#32]
El pie de página debe incluir 2 secciones:
- Enlaces
   - Conócenos (https://angular.lat/acerca)
   - Código de conducta (https://angular.lat/coc)
   - Regístrate (https://goo.gl/forms/MZa4w3AeILjsoTGA2)
   - Chat (https://chat.angular.lat/)
   - Términos (https://angular.lat/terminos)
   - Soporte (soporte@angular.lat)
- Sociales
   - Twitter (https://twitter.com/AngularHispana)
   - Facebook (https://www.facebook.com/ComunidadAngularHispano)

Centrado en la parte inferior del pie de página en texto pequeño debe estar lo siguiente:
Todos los derechos reservados. Política de privacidad (enlace TBD)

**Comment by Splaktar** [comment]
@AXEL1988 esto podría interesarte

**Comment by AXEL1988** [comment]
@Splaktar gracias ahora esta listo.
