### ISSUE TITLE
Crear una guía para organizar un nuevo meetup

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#36]
Esta pregunta surgió en el chat (https://chat.angular.lat/default/pl/7itb4ci3iig3dkwq1tp6ii9ria) y creo que sería útil para muchas personas.

Como referencia, GDG creó este gitbook: https://gdg-wisdom.gitbooks.io/wisdom-2017/content/

Esto sería útil para
- @christianmorante 
- @AXEL1988 
- @edu1998
- y más

**Comment by nicoavila** [comment]
Muy intresante! Está buena la idea. Me sumo a ayudar si es factible.

**Comment by Splaktar** [comment]
@jorgeucano @Villanuevand @GuzmanPI un Angulareando pronto puede cubrir formando un nuevo grupo?

**Comment by brolag** [comment]
Yo había desarrollado un poco esta idea en un artículo que escribí hace un tiempo y en un documento para GDG Pura Vida, quizás sea de utilidad. Por favor siéntanse en toda libertad de mejorar la propuesta.

Dejo el artículo por aquí: https://www.brolag.com/como-fabricar-oportunidades-por-medio-de-la-comunidad-de-desarrolladores-de-software/



**ACERCA DE COMO INICIAR**

1. **Empiece con poco.** No es necesario empezar con un evento gigante y miles de seguidores. Tomar un café con un grupo de amigos y hablar de algún tema es perfectamente un evento válido. Recomendamos utilizar https://www.meetup.com/es-ES/ ya que permite controlar e e identificar a los asistentes/

2. **El contenido se puede generar de muchas formas**, una pequeña charla es de bastante aporte también. En mi experiencia personal, generar eventos de manera constante y regular (cada semana o cada mes por ejemplo) da los mejores resultados. Un evento puede constar de 2 a 3 charlas de 30 minutos, esto no es demasiado cansado para las personas que asistan y además al ser poco tiempo, es factible realizarlo casi cualquier día de la semana. Expondré más detalles en un futuro artículo.

3. **Elija un lugar**. Las universidades son un excelente punto de inicio. Las universidades agradecerán cualquier  iniciativa que beneficie a sus estudiantes. Abriendo sus puertas a quien quiera compartir conocimientos y experiencias de calidad, y de manera gratuita.
 
4. **Elija un tema**. El tema debe ser específico para que las personas que asistan sepan que van a escuchar. Además, es mucho más fácil mantener un hilo conductual a lo largo del evento, generando también un espacio para la discusión.

5. **Elija a los expositores**. Nuestros colegas de oficina o amigos del gremio podrían estar interesados en compartir sus conocimientos, si no tienen experiencia previa en oratoria, posiblemente la idea les parezca atractiva y novedosa.
 
6. **Defina fecha, hora**. Elija un horario en el que todos los involucrados coincidan, preferiblemente con unas 3 semanas de anticipación mínimo.
 
7. **Publique el evento**. Comparta el evento con sus colegas, en redes sociales, y en la universidad, pidiendo a ellos que compartan también con sus redes.

**ACERCA DE LOS FORMATOS DE EVENTO**

**Café tecnológico**
Charla técnica sobre un tema durante unos 40 minutos. La idea es reunirse alrededor de un tema durante la hora del almuerzo / café, con la intención de presentar el tema y habilitar la discusión o Q / A. Capacidad: 15 ~ 20 personas. Duración: 1 hora.

**Meetup** 
Consiste en un pequeño evento con 2 o 3 charlas de 40 minutos. Requiere un lugar condicionado para presentar (requiere un proyector, tal vez un micrófono). Capacidad: 20 ~ 60 personas. Duración: 1 - 2 horas.

**Meetup en línea**
Consiste en un pequeño evento con 2 o 3 charlas de 40 minutos. Requiere poder transmitir en vivo por medio de una plataforma de streaming, como YouTube Live. Capacidad: Ilimitada. . Duración: 1 - 2 horas.

**Grupo Mastermind**
Pequeño grupo de estudio para personas que desean aprender o hablar sobre un tema, libro o tecnología específicos. Consiste en reuniones pequeñas y rápidas de reagrupación (de 1 hora a 2 horas como máximo), donde todos los participantes (o algunos de ellos previamente acordados) pueden compartir sus ideas, plantear preguntas o presentar una solución específica a un problema. Requiere una persona que actuará como facilitador para mediar y liderar el Grupo Mastermind. Todos los miembros del equipo deben tener una comunicación constante y es recomendable tener un lugar para compartir contenido y registrar las notas de las reuniones. Las sesiones se pueden realizar en línea o fuera de línea en un lugar que fomente la conversación.
Capacidad: 3 ~ 8 personas.
Duración: 1 ~ 2 horas

**Taller**
Serie de sesiones diseñadas para hacer que un grupo de personas aprenda una habilidad o tecnología específica. Debe ser muy específico, o no tan profundo debido a la brevedad del evento, sin embargo, permite a los participantes practicar en torno al tema elegido. Requiere la intervención de un entrenador o líder que compartirá el contenido y guiará los ejercicios de práctica. Puede realizarse en línea o en un laboratorio o salón de clase bien acondicionado (requiere proyector, pizarra, marcadores). Requiere un objetivo de aprendizaje específico y también una forma de medir los resultados.
Capacidad: 10 ~ 30 personas. Duración: 1.5 ~ 2 horas por sesión. Hasta 3 sesiones.

**Study Jam**
Serie de sesiones destinadas a capacitar a un grupo de personas en torno a una tecnología o conjunto de habilidades específicas. Las sesiones de entrenamiento se realizarán una tras otra durante uno o varios días. Los participantes deberán practicar y estar expuestos a mucha información durante la sesión de capacitación, por lo que se supone que es un evento muy intenso. Puede realizarse en línea o en un lugar o sala de clase bien acondicionado (requiere proyector, pizarra, bolígrafo). Requiere un objetivo de aprendizaje específico y también una forma de medir los resultados.
Capacidad: 20 ~ 40 personas.
Longitud: depende de la lista de contenidos.

**Conferencia**
Serie de sesiones con el objetivo de compartir conocimientos en diferentes temas o temas generales que ocurren en paralelo en el mismo lugar. Requiere varias aulas o salas de conferencias. Se puede ver como una combinación de Meetups y Talleres que se realizan al mismo tiempo durante el mismo día. Capacidad: 150 a 600 personas. Duración: 1 ~ 3 días.


**ACERCA DE LOS FORMATOS DE CONTENIDO**
Es importante recordar que la comunidad puede organizarse para desarrollar otros tipos de contenido como por ejemplo podcast, videos, cursos, artículos y tutoriales, dependiendo de las necesidades de los asistentes, recomendamos realizar una pequeña en cuesta para conocer mejor a la comunidad y poder ofrecer el mejor formato de contenido junto con las reuniones que se realicen.

**Comment by Splaktar** [comment]
PR https://github.com/angular-hispano/angular-hispano/pull/67 comenzó a poner esto junto. Aún queda trabajo por hacer en los TBD y se necesita hacer alguna revisión / aportación adicional sobre el contenido.

**Comment by Splaktar** [comment]
@all-contributors please add @brolag for content

**Comment by Splaktar** [comment]
https://angular.lat/organizar/meetup
