### ISSUE TITLE
Crear una guía para colaborar en la página de la comunidad o proyectos relacionados

### ISSUE THREAD

**Issue by suga0828** [angular-hispano/angular-hispano#39]
Se podría crear una guía con los lineamientos a seguir para colaborar con el desarrollo de la página de la comunidad. Especialmente para las personas que no han colaborado en otros proyectos de código abierto y tal vez no tienen mucha destreza o conocimientos del proceso para colaborar.

Pueden dar sugerencias para establecer estos parámetros.

Adicionalmente se podría crear una plantilla para crear _issues_.

**Comment by Splaktar** [comment]
Si, necesitamos esto. Creo que esta rastrado por https://github.com/angular-hispano/angular-hispano/issues/30

**Comment by AXEL1988** [comment]
Me parece genial tener una guía antes de empezar, por ejemplo se podría colocar que temas se debería manejar y a que nivel es necesario el conocimiento para que no se dificulte la colaboración.

**Comment by Splaktar** [comment]
Por favor, continuar en #30.

**Comment by Splaktar** [comment]
@all-contributors please add @suga0828 for ideas
