### ISSUE TITLE
Crear una pagina para una lista de meetups

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#46]
Hemos terminado el primer borrador de nuestra página de conferencias (https://github.com/angular-hispano/angular-hispano/issues/24), pero eso me hizo pensar que sería bueno tener una página donde la gente pudiera encuentra una lista de Meetups.

Meetup.com es bueno para encontrar reuniones cerca de usted, pero si las personas viajan o buscan reuniones que quieran que se presenten, esta lista podría ser muy valiosa para ellos.

Si desea que su reunión aparezca en el primer borrador de esta página, publique aquí la URL de tu comunidad.

**Comment by jorgeucano** [comment]
https://www.meetup.com/es-ES/NG-BAIRES/

**Comment by vanessamarely** [comment]
She Codes Angular 👉http://meetu.ps/c/4c8yM/bykrj/d on Meetup

**Comment by AXEL1988** [comment]
Dejo este comentario para dar a conocer que las cuentas en Meetup.com tiene un costo para crear un grupo. ¿Tal vez lo estoy haciendo  mal?

**Comment by jorgeucano** [comment]
si, tienen un costo semestral

**Comment by Splaktar** [comment]
@AXEL1988 Todavía no he pensado demasiado en el diseño de la página. Por ahora, ¿qué información se debe incluir?

- Nombre del Meetup
- Ciudad, País
- URL de Meetup.com

¿Algo más?

¿Deberíamos ser visuales con la imagen del encabezado Meetup.com para el grupo? o su icono?

**Comment by CarlosAngulo** [comment]
- Angular Medellín
- Medellín - Colombia
- https://www.meetup.com/es-ES/Angular-Medellin/
- Encabezado y logotipos: https://drive.google.com/drive/folders/1tvMPdUD-0oorb_PdpvU0mDNMo9bonMe6?usp=sharing

Muchas gracias!

**Comment by Villanuevand** [comment]
@jorgeucano la url en meetup de ngBaires no Existe... Podrías darlnos alguna url de referencia? 

@vanessamarely Podrías por favor hacernos llegar la imagen de She Codes Angular

@AXEL1988 Angular Quito todavía no está en Meetup?

**Comment by AXEL1988** [comment]
@Villanuevand si tenemos cuenta https://www.meetup.com/angularQuito/ 🙂

**Comment by Villanuevand** [comment]
@AXEL1988 podrías por favor enviarme 
- Nombre
- Ciudad
- Pais
- Logo

Gracias mi pana.

**Comment by ni500** [comment]
Acá va @Villanuevand 🤘

Nombre: Angular Bogotá
Ciudad: Bogotá, Colombia
País: Colombia 🇨🇴
Logo: https://drive.google.com/drive/folders/19acMQ9sZHRrMNAIx7TH0SXWWzyiQJQSq?usp=sharing

Página en meetup: https://www.meetup.com/es-ES/Angular-Bogota/

**Comment by AXEL1988** [comment]
Genial bro @Villanuevand ,
Nombre: Angular Quito
Ciudad: Quito
País: Ecuador
Logo: https://drive.google.com/file/d/14iwyOzz9QncpQlFa-1lAv5Ts68WdMK69/view?usp=sharing

**Comment by Splaktar** [comment]
@all-contributors please add @jorgeucano for content

**Comment by Splaktar** [comment]
@all-contributors please add @vanessamarely for content

**Comment by Splaktar** [comment]
@all-contributors please add @CarlosAngulo for content

**Comment by Splaktar** [comment]
@all-contributors please add @ni500 for content

**Comment by Splaktar** [comment]
@all-contributors please add @jorgeucano for question
