### ISSUE TITLE
Configurar CircleCI

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#48]
**¿Está su solicitud de función relacionada con un problema? Por favor describa.**
Necesitamos CI para validar los PRs (ahora con solo stylelint y tslint pero más tarde con pruebas).

**Describe la solución que te gustaría**
CircleCI esta usado por el equipo Angular. Un [ejemplo](https://github.com/angular/material/blob/master/.circleci/config.yml).

**Describe las alternativas que has considerado**
Antes Angular usaba TravisCI, pero han sido varios problemas. 
No conozco nada de los características de Azure.

**Contexto adicional**
N/A

**Comment by mahcr** [comment]
@Splaktar  yo puedo trabajar en esto

**Comment by mahcr** [comment]
Tarde pero seguro :D
