### ISSUE TITLE
Mejorar el SEO de sitio

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#50]
**¿Está su solicitud de función relacionada con un problema? Por favor describa.**
Mejorar el SEO y previstas de enlaces

**Describe la solución que te gustaría**
Usar los `meta` tags, manifest, etc. ([ejemplo](https://github.com/DevIntent/angular-example/blob/master/src/index.html))

**Describe las alternativas que has considerado**
- info en https://developers.google.com/web/fundamentals/web-app-manifest/
- heramienta para generar los iconos - https://realfavicongenerator.net/

**Contexto adicional**
- En Twitter, no tenemos ningun prevista - https://twitter.com/ngGuayaquil/status/1124049318917410816
- En Facebook, solo es texto sin descripción
![Screen Shot 2019-06-06 at 19 12 07](https://user-images.githubusercontent.com/3506071/59072046-0f4e4780-888f-11e9-8add-94221e6462a2.png)
- En Google, solo tenemos el descripción pero no los enlaces como angular.io
![Screen Shot 2019-06-06 at 19 14 01](https://user-images.githubusercontent.com/3506071/59072122-5b998780-888f-11e9-9c00-8982094bcd2d.png)
![Screen Shot 2019-06-06 at 19 15 09](https://user-images.githubusercontent.com/3506071/59072142-72d87500-888f-11e9-9f68-8a4c3a4480e6.png)

**Comment by Splaktar** [comment]
After we make the updates to the `index.html`, we can deploy the site and validate it via some of these tools:
- https://developers.facebook.com/tools/debug/
- https://smo.knowem.com/
- https://metatags.io/
- https://search.google.com/structured-data/testing-tool

You can try with a URL like `medium.com` to see what we want to achieve. If you put in `angular.lat` mostly it will be empty until we deploy the new `index.html` updates.

**Comment by Splaktar** [comment]
- [Google Structured Data Docs](https://developers.google.com/search/docs/guides/intro-structured-data)
- [Facebook Open Graph Docs](https://developers.facebook.com/docs/sharing/webmasters#markup)
- [Twitter Cards Docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started)

**Comment by Villanuevand** [comment]
Definitivamente debemos implementar los `meta` de Facebook y Twitter para tener alguna previsualización aceptable.

Me he asignado esta tarea, no se si @AXEL1988  ya haya adelantado algo

**Comment by Splaktar** [comment]
Sí, Axel estaba en el proceso o aprendiendo acerca de estas diferentes meta etiquetas y las configuraciones para compartir en las redes sociales. Pero aún no ha enviado un PR o ha comenzado la imposición actual.

**Comment by Villanuevand** [comment]
@Splaktar 

Ayer hablé con @AXEL1988 y me comentó que no lo había empezado, por eso decidí tomarlo yo. 
Estoy atento a cualquier comentario en el PR

**Comment by AXEL1988** [comment]
En efecto @Splaktar estaba documentándome para la tarea, sin embargo hablamos con @Villanuevand y ahora está ya listo un PR.
Esto está genial 😀
