### ISSUE TITLE
Menú principal se cierra bajo una acción especifica

### ISSUE THREAD

**Issue by Villanuevand** [angular-hispano/angular-hispano#51]
**Describe el error**
El menú principal del sitio se cierra cuando se hace una serie de acciones muy puntuales.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Vaya al sitio web de la comunidad [https://angular.lat/](https://angular.lat/)
2. Una vez allí, haga clic en cualquier parte (que no disparé una acción) del menú de opciones.
3. Después de haber hecho click, presione la tecla `ESC`. 
4. ver el error.

**Comportamiento esperado**
El menu de opciones siempre debería de estar visible, sin posibilidad de ocultarse (por ahora). 

**Capturas de pantalla**

<img width="1440" alt="Captura de Pantalla 2019-06-08 a la(s) 13 10 54" src="https://user-images.githubusercontent.com/1209238/59149674-f8bf0200-89ee-11e9-9b37-3b03c3128de4.png">

**Detalles:**
  - OS: macOS Movaje, v10.14.5
  - Navegador: 
     - Google Chrome _Versión 74.0.3729.169 (Build oficial) (64 bits)_
     - Firefox  _Versión 67.0 (64 bits)_

**Comment by Splaktar** [comment]
@all-contributors please add @Villanuevand for bug
