### ISSUE TITLE
Configurar PWA

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#64]
**¿Está su solicitud de función relacionada con un problema? Por favor describa.**
Añadir una `manifest.json` y la configuración de `meta` y `link` tags para los iconos. ([ejemplo de `index.html`](https://github.com/DevIntent/angular-example/blob/master/src/index.html), [ejemplo de `manifest.json`](https://github.com/DevIntent/angular-example/blob/master/src/manifest.json))

**Describe la solución que te gustaría**
- info en https://developers.google.com/web/fundamentals/web-app-manifest/
- heramienta para generar los iconos - https://realfavicongenerator.net/

**Contexto adicional**
Vamos a hacer `@angular/service-worker` en otra issue.

Relacionado con https://github.com/angular-hispano/angular-hispano/issues/50
Depende de https://github.com/angular-hispano/angular-hispano/issues/27

**Comment by mahcr** [comment]
Working on it! :D @Splaktar, @Villanuevand  me pueden asignar este issue
