### ISSUE TITLE
conferencias: eliminar los CFP que se han cerrado

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#74]
**¿Está su solicitud de función relacionada con un problema? Por favor describa.**
ngSpain y NG Bolivia CFPs han cerrado.

**Describe la solución que te gustaría**
Vamos a eliminar los enlaces.

**Contexto adicional**
Ninguno

**Comment by Splaktar** [comment]
@AXEL1988 ¿Estás interesado en este?

**Comment by AXEL1988** [comment]
Claro que si 🙂
