### ISSUE TITLE
http no se reenvía a https correcto

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#80]
**Describe el error**
http://chat.angular.lat se reenvía a https://34.73.29.94/login en lugar de https://chat.angular.lat. Debe haber algún problema de configuración en la configuración de Nginx después de la última actualización.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a http://chat.angular.lat

**Comportamiento esperado**
Se abre https://chat.angular.lat

**Detalles:**
  - OS: macOS
  - Navegador Chrome
  - Versión 76

**Contexto adicional**
También el certificado de Let's Encrypt expira el 2 de sept.

**Comment by orestes** [comment]
Quería echar una mano en esta issue pero no veo en el repo la configuración de nginx. ¿Tal vez podríamos tener un repo "operaciones" o similar?

**Comment by Splaktar** [comment]
Por ahora, todo está alojado en Google Compute Engine. Se implementó usando Deployment Manager y una configuración de Mattermost de Bitnami.

Puedo darle permisos para que mire a su alrededor, tal vez pueda averiguar qué archivo de configuración necesita actualizarse.

Desafortunadamente, en este momento, nada está controlado por la versión y Mattermost no proporciona ningún tipo de actualizaciones orquestadas. Por lo tanto, hay algunos pasos manuales necesarios en cada actualización. Empecé a documentar algunos de ellos en https://github.com/angular-hispano/angular-hispano/blob/master/docs/admin/upgrade-mattermost.md

**Comment by orestes** [comment]
A juzgar por ese documento (¡buen trabajo!) el proceso es un buen candidato para meter en un role de Ansible. Voy a utilizar el doc para hacer una versión inicial y comprobar que arranque una versión nueva con esos cambios.

¿Te parece bien si mantenemos todo en este repo? ¿O deberíamos separarlo en otro que se llame ops/devops?

**Comment by Splaktar** [comment]
Realmente depende de qué tan grandes serán las cosas adicionales de DevOps. Si solo son un par de MB o menos, entonces está bien aquí. Si va a ser de 5+ MB, entonces deberíamos comenzar un nuevo repositorio.

Le di acceso al Visor a todo el proyecto. Avíseme si eso le permite iniciar sesión en la VM GCE.

**Comment by Splaktar** [comment]
Antes
```nginx
server {
   listen         80 default_server;
    server_name    34.73.29.94;
   return         301 https://$server_name$request_uri;
}
```
Despues
```nginx
server {
   listen         80 default_server;
    server_name    34.73.29.94;
   return         301 https://chat.angular.lat$request_uri;
}
```
