### ISSUE TITLE
Traducción "tickets" -> "boletas"

### ISSUE THREAD

**Issue by orestes** [angular-hispano/angular-hispano#82]
Quería preguntar si en latinoamérica hay otra palabra para "boletas" (tickets). En España utilizamos "entradas" (a veces incluso ponemos "tickets"). Tal vez sería mas inclusiva.

https://github.com/angular-hispano/angular-hispano/blob/master/projects/web/src/app/conferences/conferences.component.html#L18

**Comment by Splaktar** [comment]
¿No usan la palabra Boletas en España?

**Comment by orestes** [comment]
No, utilizamos entradas. Entendemos boletas, pero es muy ajena al lenguaje normal.
Envía una PR entonces :)

**Comment by Splaktar** [comment]
@all-contributors please add @orestes for bug
