### ISSUE TITLE
Investigue traduciendo angular.io

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#9]
Hablé con @jorgeucano hace unas semanas y él iba a investigar el estado actual de AIO (angular.io) y la mejor manera de manejar la traducción. Ayudaré con este proceso también una vez que reciba sus comentarios iniciales.

For reference, https://github.com/angular/angular-es fue un esfuerzo relacionado que dejó de funcionar en septiembre de 2016.

También hay versiones en japonés y chino:
- https://github.com/angular/angular-ja
- https://github.com/angular/angular-cn/tree/aio

**Comment by jorgeucano** [comment]
estoy trabajando en eso, ya tengo la documentación y estoy viendo como separarla para poder hacer una traduccion "rapida"

**Comment by orestes** [comment]
¿Puedo ayudar con esto?

**Comment by Splaktar** [comment]
Hoy, la siguiente pregunta se publicó en el chat en https://www.youtube.com/watch?v=8nySZwvU0LE:

> Gustavo Alvarez:
> Aprovechando tu comentario Jorge, sabes si alguien está trabajando en una versión en español de la doc de ng? En mi comunidad el nivel de inglés es muy malo y me preguntan mucho por recursos en español.

**Comment by Splaktar** [comment]
Aquí hay una alternativa para reconstruir AIO que es de acceso público y donde puede editar y alojar traducciones fácilmente:
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#In_this_module

React, Vue, Ember tienen documentos allí con algunos artículos traducidos al portugués, mandarín y japonés.

**Comment by Splaktar** [comment]
Este enfoque también permite que este contenido se desarrolle con el tiempo, artículo por artículo. También permite una fácil distribución del trabajo a múltiples personas.

**Comment by Villanuevand** [comment]
Creo que es una buena oportunidad para colaborar con Angular...

**Comment by devpato** [comment]
Hola,

Para los que no estaban presentes en la llamada  GDE Angular de ayer Stephen (DevRel Angular team) menciono que estaria cool tener el sitio en de Angular.io en Espanol y yo me ofreci a ayudar asi que estoy buscando quien dentro de este issue que sigue interesado en colaborar. Gracias a @Splaktar  por dirigirme a esta issue :)

**Comment by Villanuevand** [comment]
Hola @devpato 
Gracias por extender la invitacion a cooperar..

Esta ha sido una iniciativa que personalmente siempre he querido que se baje desde el equipo de Angular, que bueno que eso haya ocurrido. 
Puedes contar conmigo...

**Comment by devpato** [comment]
@Villanuevand Andres! que cool contar contigo. me podrias proporcionar tu correo (me lo puedes mandar por twitter si gustas) para invitarte una llamada con todos la siguiente semana

**Comment by Splaktar** [comment]
Si fuera útil, puedo crear un canal para este esfuerzo en https://chat.angular.lat.

También sería posible comenzar una discusión más amplia sobre esto en GitHub Discussions: https://github.com/angular-hispano/angular-hispano/discussions

**Comment by Villanuevand** [comment]
@Splaktar Estaría genial el momento para usar [Discussions](https://github.com/angular-hispano/angular-hispano/discussions)

**Comment by Splaktar** [comment]
Todas las tareas de documentación ahora se rastrean en https://github.com/angular-hispano/angular/issues.
