### ISSUE TITLE
pwa: solicitar al usuario que actualice la aplicación

### ISSUE THREAD

**Issue by Splaktar** [angular-hispano/angular-hispano#94]
**¿Está su solicitud de función relacionada con un problema? Por favor describa.**
Los usuarios pueden regresar al sitio y ver contenido obsoleto sin saber que hay una nueva versión disponible. Si se vuelven a cargar un par de veces, verán el nuevo contenido, pero debemos informarles cuando haya una nueva versión disponible.

**Describe la solución que te gustaría**
solicitar al usuario que actualice la aplicación cuando haya una nueva versión disponible

**Describe las alternativas que has considerado**
https://angular.io/guide/service-worker-communications#swupdate-service

**Comment by LuisReinoso** [comment]
Hola.. Me pueden ayudar uniendome al repo para contribuir con este issue. Github me dice que no tengo los permisos. O debo hacer un fork del repo.? Mi nombre de usuario es @LuisReinoso
> remote: Permission to angular-hispano/angular-hispano.git denied to LuisReinoso.

Gracias! :')

**Comment by LuisReinoso** [comment]
![imagen](https://user-images.githubusercontent.com/7484215/72201322-9f093500-3420-11ea-808f-547301502312.png)

**Comment by Splaktar** [comment]
@LuisReinoso si, voy a hacerlo ahora.
